// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyRail.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotifyRail.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotifyRailDbContext))]
    [Migration("20260724125342_CorrelateDeliveryTraces")]
    partial class CorrelateDeliveryTraces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotifyRail.Api.Features.ApiClients.Persistence.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("api_clients", null, t =>
                        {
                            t.HasCheckConstraint("api_clients_disabled_at_check", "(is_enabled AND disabled_at IS NULL) OR (NOT is_enabled AND disabled_at IS NOT NULL)");

                            t.HasCheckConstraint("api_clients_name_check", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.ApiClients.Persistence.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_prefix");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("LookupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lookup_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("VerificationHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("verification_hash");

                    b.HasKey("Id");

                    b.HasIndex("ApiClientId");

                    b.HasIndex("LookupId")
                        .IsUnique()
                        .HasDatabaseName("api_keys_lookup_id_key");

                    b.ToTable("api_keys", null, t =>
                        {
                            t.HasCheckConstraint("api_keys_display_prefix_check", "btrim(display_prefix) <> ''");

                            t.HasCheckConstraint("api_keys_lookup_id_check", "btrim(lookup_id) <> ''");

                            t.HasCheckConstraint("api_keys_verification_hash_check", "octet_length(verification_hash) = 32");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Deliveries.Persistence.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("SourceTraceParent")
                        .HasColumnType("text")
                        .HasColumnName("source_trace_parent");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasDatabaseName("deliveries_provider_message_id_idx")
                        .HasFilter("provider_message_id IS NOT NULL");

                    b.HasIndex("MessageId", "Recipient")
                        .IsUnique()
                        .HasDatabaseName("deliveries_message_id_recipient_key");

                    b.HasIndex("Status", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("deliveries_due_idx")
                        .HasFilter("status IN ('queued', 'retry_scheduled')");

                    b.ToTable("deliveries", null, t =>
                        {
                            t.HasCheckConstraint("deliveries_attempt_count_check", "attempt_count >= 0");

                            t.HasCheckConstraint("deliveries_claim_check", "(status <> 'processing' AND claimed_at IS NULL AND claimed_by IS NULL) OR (status = 'processing' AND claimed_at IS NOT NULL AND claimed_by IS NOT NULL AND btrim(claimed_by) <> '')");

                            t.HasCheckConstraint("deliveries_provider_message_id_check", "provider_message_id IS NULL OR btrim(provider_message_id) <> ''");

                            t.HasCheckConstraint("deliveries_recipient_check", "btrim(recipient) <> ''");

                            t.HasCheckConstraint("deliveries_retry_schedule_check", "(status = 'retry_scheduled' AND next_attempt_at IS NOT NULL) OR (status <> 'retry_scheduled' AND next_attempt_at IS NULL)");

                            t.HasCheckConstraint("deliveries_source_trace_parent_check", "source_trace_parent IS NULL OR btrim(source_trace_parent) <> ''");

                            t.HasCheckConstraint("deliveries_status_check", "status IN ('queued', 'processing', 'sent', 'delivered', 'retry_scheduled', 'failed', 'expired')");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Deliveries.Persistence.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("delivery_attempts_delivery_id_attempt_number_key");

                    b.ToTable("delivery_attempts", null, t =>
                        {
                            t.HasCheckConstraint("delivery_attempts_attempt_number_check", "attempt_number > 0");

                            t.HasCheckConstraint("delivery_attempts_error_code_check", "error_code IS NULL OR btrim(error_code) <> ''");

                            t.HasCheckConstraint("delivery_attempts_error_message_check", "error_message IS NULL OR btrim(error_message) <> ''");

                            t.HasCheckConstraint("delivery_attempts_outcome_check", "outcome IN ('accepted', 'retryable_failure', 'permanent_failure')");

                            t.HasCheckConstraint("delivery_attempts_provider_check", "btrim(provider) <> ''");

                            t.HasCheckConstraint("delivery_attempts_provider_message_id_check", "provider_message_id IS NULL OR btrim(provider_message_id) <> ''");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Messages.Persistence.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_client_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Encoding")
                        .HasColumnType("text")
                        .HasColumnName("encoding");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ReportLabel")
                        .HasColumnType("text")
                        .HasColumnName("report_label");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SenderTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ApiClientId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("messages_api_client_id_idempotency_key_key");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("messages_body_check", "btrim(body) <> ''");

                            t.HasCheckConstraint("messages_channel_check", "channel = 'sms'");

                            t.HasCheckConstraint("messages_encoding_check", "encoding IN ('latin', 'turkish', 'unicode')");

                            t.HasCheckConstraint("messages_idempotency_key_check", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("messages_sender_title_check", "btrim(sender_title) <> ''");

                            t.HasCheckConstraint("messages_type_check", "type IN ('otp', 'transactional', 'campaign')");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Otp.Persistence.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempt_count");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("otp_challenges_message_id_key");

                    b.HasIndex("Recipient", "ExpiresAt")
                        .HasDatabaseName("otp_challenges_recipient_expiry_idx");

                    b.ToTable("otp_challenges", null, t =>
                        {
                            t.HasCheckConstraint("otp_challenges_attempts_check", "max_attempts > 0 AND failed_attempt_count >= 0 AND failed_attempt_count <= max_attempts");

                            t.HasCheckConstraint("otp_challenges_code_hash_check", "octet_length(code_hash) = 32");

                            t.HasCheckConstraint("otp_challenges_expiry_check", "expires_at > created_at");

                            t.HasCheckConstraint("otp_challenges_recipient_check", "btrim(recipient) <> ''");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<long>("LatencyMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_milliseconds");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_event_id");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("webhook_attempts_event_id_attempt_number_key");

                    b.ToTable("webhook_attempts", null, t =>
                        {
                            t.HasCheckConstraint("webhook_attempts_attempt_number_check", "attempt_number > 0");

                            t.HasCheckConstraint("webhook_attempts_error_code_check", "error_code IS NULL OR (btrim(error_code) <> '' AND char_length(error_code) <= 100)");

                            t.HasCheckConstraint("webhook_attempts_error_message_check", "error_message IS NULL OR (btrim(error_message) <> '' AND char_length(error_message) <= 500)");

                            t.HasCheckConstraint("webhook_attempts_http_status_code_check", "http_status_code IS NULL OR http_status_code BETWEEN 100 AND 599");

                            t.HasCheckConstraint("webhook_attempts_latency_check", "latency_milliseconds >= 0");

                            t.HasCheckConstraint("webhook_attempts_outcome_check", "outcome IN ('succeeded', 'retryable_failure', 'permanent_failure')");

                            t.HasCheckConstraint("webhook_attempts_time_check", "completed_at >= attempted_at");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ApiClientId")
                        .IsUnique()
                        .HasDatabaseName("webhook_endpoints_active_api_client_id_key")
                        .HasFilter("is_enabled");

                    b.HasIndex("ApiClientId", "CreatedAt")
                        .HasDatabaseName("webhook_endpoints_api_client_created_at_idx");

                    b.ToTable("webhook_endpoints", null, t =>
                        {
                            t.HasCheckConstraint("webhook_endpoints_disabled_at_check", "(is_enabled AND disabled_at IS NULL) OR (NOT is_enabled AND disabled_at IS NOT NULL)");

                            t.HasCheckConstraint("webhook_endpoints_url_check", "btrim(url) <> ''");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApiClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_client_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("AutomaticAttemptDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("automatic_attempt_deadline_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_at");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WebhookEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_endpoint_id");

                    b.HasKey("Id");

                    b.HasIndex("ApiClientId");

                    b.HasIndex("MessageId");

                    b.HasIndex("WebhookEndpointId");

                    b.HasIndex("DeliveryId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("webhook_events_delivery_id_sequence_key");

                    b.HasIndex("Status", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("webhook_events_due_idx");

                    b.ToTable("webhook_events", null, t =>
                        {
                            t.HasCheckConstraint("webhook_events_attempt_count_check", "attempt_count >= 0");

                            t.HasCheckConstraint("webhook_events_claim_check", "(status = 'processing' AND claimed_at IS NOT NULL AND btrim(claimed_by) <> '') OR (status <> 'processing' AND claimed_at IS NULL AND claimed_by IS NULL)");

                            t.HasCheckConstraint("webhook_events_dead_at_check", "status <> 'dead' OR dead_at IS NOT NULL");

                            t.HasCheckConstraint("webhook_events_payload_check", "btrim(payload) <> ''");

                            t.HasCheckConstraint("webhook_events_retry_schedule_check", "(status = 'retry_scheduled' AND next_attempt_at IS NOT NULL) OR (status <> 'retry_scheduled' AND next_attempt_at IS NULL)");

                            t.HasCheckConstraint("webhook_events_sequence_check", "sequence > 0");

                            t.HasCheckConstraint("webhook_events_status_check", "status IN ('pending', 'processing', 'retry_scheduled', 'succeeded', 'dead')");

                            t.HasCheckConstraint("webhook_events_succeeded_at_check", "(status = 'succeeded' AND succeeded_at IS NOT NULL) OR (status <> 'succeeded' AND succeeded_at IS NULL)");

                            t.HasCheckConstraint("webhook_events_type_check", "btrim(type) <> ''");

                            t.HasCheckConstraint("webhook_events_version_check", "version > 0");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("protected_value");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiClientId")
                        .IsUnique()
                        .HasDatabaseName("webhook_secrets_active_api_client_id_key")
                        .HasFilter("retired_at IS NULL");

                    b.HasIndex("ApiClientId", "CreatedAt")
                        .HasDatabaseName("webhook_secrets_api_client_created_at_idx");

                    b.ToTable("webhook_secrets", null, t =>
                        {
                            t.HasCheckConstraint("webhook_secrets_protected_value_check", "octet_length(protected_value) > 0");

                            t.HasCheckConstraint("webhook_secrets_retired_at_check", "retired_at IS NULL OR retired_at >= created_at");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.ApiClients.Persistence.ApiKey", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.ApiClients.Persistence.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("ApiClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Deliveries.Persistence.Delivery", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.Messages.Persistence.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("deliveries_message_id_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Deliveries.Persistence.DeliveryAttempt", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.Deliveries.Persistence.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("delivery_attempts_delivery_id_fkey");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Messages.Persistence.Message", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.ApiClients.Persistence.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("ApiClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Otp.Persistence.OtpChallenge", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.Messages.Persistence.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("otp_challenges_message_id_fkey");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookAttempt", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.Webhooks.Persistence.WebhookEvent", null)
                        .WithMany()
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookEndpoint", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.ApiClients.Persistence.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("ApiClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookEvent", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.ApiClients.Persistence.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("ApiClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NotifyRail.Api.Features.Deliveries.Persistence.Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NotifyRail.Api.Features.Messages.Persistence.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NotifyRail.Api.Features.Webhooks.Persistence.WebhookEndpoint", null)
                        .WithMany()
                        .HasForeignKey("WebhookEndpointId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Webhooks.Persistence.WebhookSecret", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.ApiClients.Persistence.ApiClient", null)
                        .WithMany()
                        .HasForeignKey("ApiClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
