// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyRail.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotifyRail.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotifyRailDbContext))]
    [Migration("20260703104217_CreateDeliveries")]
    partial class CreateDeliveries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotifyRail.Api.Features.Deliveries.Persistence.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ProviderMessageId")
                        .IsUnique()
                        .HasDatabaseName("deliveries_provider_message_id_idx")
                        .HasFilter("provider_message_id IS NOT NULL");

                    b.HasIndex("MessageId", "Recipient")
                        .IsUnique()
                        .HasDatabaseName("deliveries_message_id_recipient_key");

                    b.HasIndex("Status", "NextAttemptAt", "CreatedAt")
                        .HasDatabaseName("deliveries_due_idx")
                        .HasFilter("status IN ('queued', 'retry_scheduled')");

                    b.ToTable("deliveries", null, t =>
                        {
                            t.HasCheckConstraint("deliveries_attempt_count_check", "attempt_count >= 0");

                            t.HasCheckConstraint("deliveries_claim_check", "(status <> 'processing' AND claimed_at IS NULL AND claimed_by IS NULL) OR (status = 'processing' AND claimed_at IS NOT NULL AND claimed_by IS NOT NULL AND btrim(claimed_by) <> '')");

                            t.HasCheckConstraint("deliveries_provider_message_id_check", "provider_message_id IS NULL OR btrim(provider_message_id) <> ''");

                            t.HasCheckConstraint("deliveries_recipient_check", "btrim(recipient) <> ''");

                            t.HasCheckConstraint("deliveries_retry_schedule_check", "(status = 'retry_scheduled' AND next_attempt_at IS NOT NULL) OR (status <> 'retry_scheduled' AND next_attempt_at IS NULL)");

                            t.HasCheckConstraint("deliveries_status_check", "status IN ('queued', 'processing', 'sent', 'delivered', 'retry_scheduled', 'failed', 'expired')");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Messages.Persistence.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Encoding")
                        .HasColumnType("text")
                        .HasColumnName("encoding");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ReportLabel")
                        .HasColumnType("text")
                        .HasColumnName("report_label");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SenderTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("messages_idempotency_key_key");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("messages_body_check", "btrim(body) <> ''");

                            t.HasCheckConstraint("messages_channel_check", "channel = 'sms'");

                            t.HasCheckConstraint("messages_encoding_check", "encoding IN ('latin', 'turkish', 'unicode')");

                            t.HasCheckConstraint("messages_idempotency_key_check", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("messages_sender_title_check", "btrim(sender_title) <> ''");

                            t.HasCheckConstraint("messages_type_check", "type IN ('otp', 'transactional', 'campaign')");
                        });
                });

            modelBuilder.Entity("NotifyRail.Api.Features.Deliveries.Persistence.Delivery", b =>
                {
                    b.HasOne("NotifyRail.Api.Features.Messages.Persistence.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("deliveries_message_id_fkey");

                    b.Navigation("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
