// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotifyRail.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotifyRail.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotifyRailDbContext))]
    partial class NotifyRailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotifyRail.Api.Features.Messages.Persistence.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Encoding")
                        .HasColumnType("text")
                        .HasColumnName("encoding");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ReportLabel")
                        .HasColumnType("text")
                        .HasColumnName("report_label");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("SenderTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("messages_idempotency_key_key");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("messages_body_check", "btrim(body) <> ''");

                            t.HasCheckConstraint("messages_channel_check", "channel = 'sms'");

                            t.HasCheckConstraint("messages_encoding_check", "encoding IN ('latin', 'turkish', 'unicode')");

                            t.HasCheckConstraint("messages_idempotency_key_check", "btrim(idempotency_key) <> ''");

                            t.HasCheckConstraint("messages_sender_title_check", "btrim(sender_title) <> ''");

                            t.HasCheckConstraint("messages_type_check", "type IN ('otp', 'transactional', 'campaign')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
